name: Android Release Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"   # dispara automaticamente quando vocÃª der: git push origin v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      #  CLONE
      # -----------------------------
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # -----------------------------
      #  JDK
      # -----------------------------
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # -----------------------------
      #  CACHE do Gradle
      # -----------------------------
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v5

      # -----------------------------
      #  RESTAURAR KEYSTORE
      # -----------------------------
      - name: Restore keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ./keystore.jks

      # -----------------------------
      #  CRIAR ~/.gradle/gradle.properties
      # -----------------------------
      - name: Create gradle.properties
        run: |
          mkdir -p ~/.gradle
          cat <<EOF > ~/.gradle/gradle.properties
          RELEASE_STORE_FILE=${{ github.workspace }}/keystore.jks
          RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}
          EOF

      # -----------------------------
      #  BUILD RELEASE ASSINADO
      # -----------------------------
      - name: Build Release APK
        run: ./gradle_shared/gradlew assembleRelease

      # -----------------------------
      #  CRIAR RELEASE NO GITHUB
      # -----------------------------
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}     # usa a tag que disparou o workflow
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ðŸš€ Build gerado automaticamente.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # -----------------------------
      #  ENVIAR APK PARA A RELEASE
      # -----------------------------
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Release automÃ¡tico"
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/mapping/release/mapping.txt
          fail_on_unmatched_files: false
          retries: 5
          retry_wait_seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
