name: Restore and Upload Keystore

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  restore-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Restore Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ./keystore.jks

      - name: Upload Keystore Artifact
        uses: actions/upload-artifact@v2
        with:
          name: keystore
          path: ./keystore.jks

      - name: Delete PR Branch
        run: |
          git push origin --delete ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

